### ISSUE TITLE
MySQL geospacial search using haversine formula returns null on same point

### ISSUE THREAD

**Issue by fpolito** [sjaakp/yii2-spatial#3] opened 2019-05-19 14:43 UTC
There is a problemin function nearest (file ActiveQuery.php): in Haversine formula when the lat/lng specified in the query matches EXACTLY the lat/lng of a record in the database, some times returns NULL and not 0 for distance _d
The problem is that acos is invoked with a value which is not in the range of -1 and 1, so it returns null.
This is the solution:
replace
'_d' => "{$lenPerDegree}*DEGREES(ACOS(COS(RADIANS(:lt))*COS(RADIANS(_lat))*COS(RADIANS(:lg)-RADIANS(_lng))+SIN(RADIANS(:lt))*SIN(RADIANS(_lat))))"     // Haversine

with
'_d' => "{$lenPerDegree}*DEGREES( IFNULL(ACOS(COS(RADIANS(:lt))*COS(RADIANS(_lat))*COS(RADIANS(:lg)-RADIANS(_lng))+SIN(RADIANS(:lt))*SIN(RADIANS(_lat))),0))"     // Haversine

I have found the solution here: 
https://stackoverflow.com/questions/28254863/mysql-geospacial-search-using-haversine-formula-returns-null-on-same-point

The Haversine formula is nice and fast, but it has a ‘fatal’ flaw of returning NULL sometimes when measuring the distance between a point and itself. About 3% of latitudes have this problem; example: 60.5544. Any longitude works, because it cancels out. About 6% compute that the distance from a point to itself is a few meters.

The Vincenty formula is a more numerically stable version of the Haversine formula for computing great circle distances. The question of numerical stability comes up specifically when the distances between points are small. In those cases the cosine is very close to 1, so the inverse cosine function is not as precise as the inverse tangent function used in this formula.
For Vincenty formula see: http://www.plumislandmedia.net/mysql/vicenty-great-circle-distance-formula/

So you can implement the Vincenty formula.

**Comment by sjaakp** [comment] 2019-05-19 18:25
Wow, impressive. I never would have thought of this. Thanks!

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: fpolito <notifications@github.com> 
Verzonden: zondag 19 mei 2019 16:44
Aan: sjaakp/yii2-spatial <yii2-spatial@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-spatial] MySQL geospacial search using haversine formula returns null on same point (#3)

 

There is a problemin function nearest (file ActiveQuery.php): in Haversine formula when the lat/lng specified in the query matches EXACTLY the lat/lng of a record in the database, some times returns NULL and not 0 for distance _d
The problem is that acos is invoked with a value which is not in the range of -1 and 1, so it returns null.
This is the solution:
replace
'_d' => "{$lenPerDegree}*DEGREES(ACOS(COS(RADIANS(:lt))*COS(RADIANS(_lat))*COS(RADIANS(:lg)-RADIANS(_lng))+SIN(RADIANS(:lt))*SIN(RADIANS(_lat))))" // Haversine

with
'_d' => "{$lenPerDegree}*DEGREES( IFNULL(ACOS(COS(RADIANS(:lt))*COS(RADIANS(_lat))*COS(RADIANS(:lg)-RADIANS(_lng))+SIN(RADIANS(:lt))*SIN(RADIANS(_lat))),0))" // Haversine

I have found the solution here:
https://stackoverflow.com/questions/28254863/mysql-geospacial-search-using-haversine-formula-returns-null-on-same-point

**Comment by acorncom** [comment] 2020-03-18 13:28
Looks like this issue can be closed, it was resolved in https://github.com/sjaakp/yii2-spatial/commit/24b8fe9bfaa9016e91c253f28eb92285dda72170

**Closed as completed** 2020-03-18 13:54 UTC
